name: 'jira'
version: '0.19.0'
config-version: 2
require-dbt-version: [">=1.3.0", "<2.0.0"]

profile: dbt_hubspot  # Este nombre debe coincidir con el definido en profiles.yml

vars:
    
  #jira_database: jira
  jira_schema: jira_staging
  
  jira_using_sprints: false    # Enabled by default. Disable if you do not have the sprint table or do not want sprint-related metrics reported.
  jira_using_components: false # Enabled by default. Disable if you do not have the component table or do not want component-related metrics reported.
  jira_using_versions: false   # Enabled by default. Disable if you do not have the versions table or do not want versions-related metrics reported.
  jira_using_priorities: false # Enabled by default. Disable if you are not using priorities in Jira.
  jira_include_comments: false # Enabled by default. Disabling will remove the aggregation of comments via the `count_comments` and `conversations` columns in the `jira__issue_enhanced` table.

  jira:
    issue: "{{ ref('stg_jira__issue') }}"
    project: "{{ ref('stg_jira__project') }}"
    user: "{{ ref('stg_jira__user') }}"
    issue_type: "{{ ref('stg_jira__issue_type') }}"
    status: "{{ ref('stg_jira__status') }}"
    status_category: "{{ ref('stg_jira__status_category') }}"
    resolution: "{{ ref('stg_jira__resolution') }}"
    priority: "{{ ref('stg_jira__priority') }}"
    issue_multiselect_history: "{{ ref('stg_jira__issue_multiselect_history') }}"
    issue_field_history: "{{ ref('stg_jira__issue_field_history') }}"
    comment: "{{ ref('stg_jira__comment') }}"
    issue_link: "{{ ref('stg_jira__issue_link') }}"
    component: "{{ ref('stg_jira__component') }}"
    field: "{{ ref('stg_jira__field') }}"
    field_option: "{{ ref('stg_jira__field_option') }}"
    sprint: "{{ ref('stg_jira__sprint') }}"
    version: "{{ ref('stg_jira__version') }}"
    jira_issue_history_buffer: 1

models:
  jira:
    +materialized: table
    +schema: jira
    intermediate:
      +materialized: ephemeral
      +schema: int_jira
  jira_source:
    +schema: stg_jira # leave blank for just the target_schema