dbt_hubspot:  # Este nombre debe coincidir con el perfil definido en `dbt_project.yml`
  outputs:
    dev:
      type: "{{ env_var('DBT_DB_TYPE_DEV') }}"
      host: "{{ env_var('DBT_HOST_DEV') }}"
      port: "{{ env_var('DBT_PORT_DEV') | int }}"
      user: "{{ env_var('DBT_USER_DEV') }}"
      pass: "{{ env_var('DBT_PASSWORD_DEV') }}"
      dbname: "{{ env_var('DBT_DATABASE_DEV') }}"
      schema: "{{ env_var('DBT_SCHEMA_DEV') }}"
      threads: 4
    prod:
      type: "{{ env_var('DBT_DB_TYPE_PROD') }}"
      host: "{{ env_var('DBT_HOST_PROD') }}"
      port: "{{ env_var('DBT_PORT_PROD') | int }}"
      user: "{{ env_var('DBT_USER_PROD') }}"
      pass: "{{ env_var('DBT_PASSWORD_PROD') }}"
      dbname: "{{ env_var('DBT_DATABASE_PROD') }}"
      schema: "{{ env_var('DBT_SCHEMA_PROD') }}"
      threads: 4
  target: dev  # Define el entorno por defecto
