dbt_hubspot:  # Este nombre debe coincidir con el perfil definido en `dbt_project.yml`
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DBT_HOST_DEV') }}"
      port: "{{ env_var('DBT_PORT_DEV') | int }}"
      user: "{{ env_var('DBT_USER_DEV') }}"
      pass: "{{ env_var('DBT_PASSWORD_DEV') }}"
      dbname: "{{ env_var('DBT_DATABASE_DEV') }}"
      schema: "{{ env_var('DBT_SCHEMA_DEV') }}"
      threads: 4
    prod:
      type: postgres
      host: localhost
      port: 5432
      user: root
      password: root
      dbname: hubspot
      schema: hubspot_staging
      threads: 4
  target: dev  # Define el entorno por defecto
